### PR TITLE
Treat nested fields as STRING for traces

### PR DESCRIPTION
**Pull request by TimNooren**
Mitigation until we fix parsing downstream.

Tested using [this table definition](https://github.com/blockchain-etl/polygon-etl/blob/main/airflow/dags/resources/stages/parse/table_definitions/opensea/ZeroExFeeWrapper_call_matchOrders.json) where we recently had to change fields defined as `RECORD` to `STRING`. Parser output is now the same.

### CODE REVIEW

**Review by araa47 — DISMISSED** [review]
Seems correct , can we although test with a few more common contracts to make sure everything is working as expected.

**Comment by TimNooren** [comment]
@araa47 Good call, thanks. Change was not correct since it also casted tuples to `STRING` for logs, but we do in fact parse tuples correctly for logs (in most cases at least), so we should use `RECORD` types there. It's only traces where we currently are not (and historically have not) parsed tuples recursively.

I tested against some more existing definitions, and found no differences for the following:
- [rarible/ExchangeV2_event_Transfer](https://github.com/blockchain-etl/ethereum-etl-airflow/blob/master/dags/resources/stages/parse/table_definitions/rarible/ExchangeV2_event_Transfer.json)
- [zora/AsksV1_1_event_ExchangeExecuted.json](https://github.com/blockchain-etl/ethereum-etl-airflow/blob/master/dags/resources/stages/parse/table_definitions/zora/AsksV1_1_event_ExchangeExecuted.json)
- [maker/Dai_call_burn.json](https://github.com/blockchain-etl/ethereum-etl-airflow/blob/master/dags/resources/stages/parse/table_definitions/maker/Dai_call_burn.json)
- [aave/LendingPool_v2_event_Borrow.json](https://github.com/blockchain-etl/ethereum-etl-airflow/blob/master/dags/resources/stages/parse/table_definitions/aave/LendingPool_v2_event_Borrow.json)

I also found one more trace definition that has tuples defined as `RECORD` (`makerBid` and `takerAsk`):
- [looksrare/LooksRareExchange_call_matchBidWithTakerAsk](https://github.com/blockchain-etl/ethereum-etl-airflow/blob/master/dags/resources/stages/parse/table_definitions/looksrare/LooksRareExchange_call_matchBidWithTakerAsk.json)

With this change those fields are instead defined as `STRING`.

As discussed, added some unit tests as well.

**Comment by araa47** [comment]
Hey @TimNooren , great work adding tests.

Improvement Suggestion: 
- Github Action to run tests on PR

Apart from that all looks good. Would suggest trying to run deployment locally to verify everything works as expected. 


Deployment process for deploying to dev and prod is documented here: https://github.com/nansen-ai/abi-parser#deployment

Note that this repo is old and structured different where the master branch is actually called `dev` -> corresponds to deploying to dev (no ci / cd exists right now)

and if everything works great you can create a PR from `dev` -> `main` , and deploy to prod (no ci / cd exists right now)

We should probably re-structure and automate these deployments in the future. Can probably visit this when we work on the improvements.

**Review by araa47 — APPROVED** [review]

**Comment by TimNooren** [comment]
Applied to dev.

**Pull request merged**
